services:
  unbound:
    image: gibsonsoft/unbound-full
    container_name: unbound
    pull_policy: never
    environment:
      CONTROL_ENABLE: yes
    build:
      context: .
      target: final
      platforms:
        - linux/amd64
        - linux/arm64/v8
        - linux/ppc64le
        - linux/arm/v6
        - linux/arm/v7
        - linux/386
        - linux/riscv64
        - linux/s390x
      args:
        ALPINE_VERSION: 3.20.2
        XX_VERSION: 1.5.0

        BUILD_THREADS: 32
        
        # Edge lld for v18 currently needed to link RISCV relocations. See https://github.com/llvm/llvm-project/issues/64102#issuecomment-2233940314
        CORE_BUILD_DEPS: >
          clang
          lld@edge=~18.1
          make
          cmake
          git
          perl
          file
          upx
          gnupg
          flex
          bison
          pkgconf
          automake
          autoconf
          libtool

        TARGET_BUILD_DEPS: >
          g++
          llvm
          compiler-rt
          llvm-libunwind
          llvm-libunwind-static
          musl-dev
          linux-headers

        PROTOBUF_BUILD_DEPS_BUILD: >
          zlib-dev
          zlib-static

        PROTOBUF_BUILD_DEPS_HOST: >
          zlib-dev
          zlib-static
        
        UNBOUND_BUILD_DEPS: >
          expat-dev
          expat-static
          libevent-dev
          libevent-static
          libsodium-dev
          libsodium-static
          nghttp2-dev
          nghttp2-static

        OPENSSL_GIT_COMMIT: fb7fab9fa6f4869eaa8fbb97e0d593159f03ffe4
        OPENSSL_SOURCE: https://github.com/openssl/openssl.git
        OPENSSL_VERSION: 3.3.2

        # Protobuf-C 1.5.0 currently doesn't cooperate with Protobuf > 25
        # Upgrade both Protobuf and Protobuf-C once PC (officially) releases an update with fixes
        PROTOBUF_GIT_COMMIT: e915ce24b3d43c0fffcbf847354288c07dda1de0
        PROTOBUF_SOURCE: https://github.com/protocolbuffers/protobuf.git
        PROTOBUF_VERSION: 25.4

        PROTOBUFC_GIT_COMMIT: 86a89d1e758557e5df60cf47ed98df837ed93428
        PROTOBUFC_SOURCE: https://github.com/protobuf-c/protobuf-c.git
        PROTOBUFC_VERSION: 1.5.0

        LDNS_GIT_COMMIT: 46f2f0035330414b1c6f19c3b8c43994a1fb766c
        LDNS_SOURCE: https://github.com/NLnetLabs/ldns.git
        LDNS_VERSION: 1.8.4

        UNBOUND_GIT_COMMIT: 79e4c578518886a32475cfbb0de383ff3a905033
        UNBOUND_SOURCE: https://github.com/NLnetLabs/unbound.git
        UNBOUND_VERSION: 1.21.0

        HIREDIS_GIT_COMMIT: 60e5075d4ac77424809f855ba3e398df7aacefe8
        HIREDIS_SOURCE: https://github.com/redis/hiredis.git
        HIREDIS_VERSION: 1.2.0

        ROOT_HINTS: https://www.internic.net/domain/named.root
        ICANN_CERT: https://data.iana.org/root-anchors/icannbundle.pem
